# K-mers analysis

## Arguments

In [1]:
fastq_tsv_path = '/opt/data_out/fastq_tsv/'
kmers_tsv_path = '/opt/data_out/kmers/'

datasets = [

    # Guppy
    # {'dataset': 'bc3_01', 'caller': 'guppy'},
    # {'dataset': 'bc3_02', 'caller': 'guppy'},
    # {'dataset': 'bc3_03', 'caller': 'guppy'},
    # {'dataset': 'bc6_05', 'caller': 'guppy'},
    # {'dataset': 'bc6_06', 'caller': 'guppy'},
    # {'dataset': 'bc6_07', 'caller': 'guppy'},
    # {'dataset': 'bc6_08', 'caller': 'guppy'},
    # {'dataset': 'bc6_09', 'caller': 'guppy'},
    # {'dataset': 'bc6_10', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_05', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_06', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_07', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_08', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_09', 'caller': 'guppy'},
    # {'dataset': 'bc6_2_10', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_05', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_06', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_07', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_08', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_09', 'caller': 'guppy'},
    # {'dataset': 'bc6_3_10', 'caller': 'guppy'},
    {'dataset': 'bc6_4_05', 'caller': 'guppy'},
    {'dataset': 'bc6_4_06', 'caller': 'guppy'},
    {'dataset': 'bc6_4_07', 'caller': 'guppy'},
    {'dataset': 'bc6_4_08', 'caller': 'guppy'},
    {'dataset': 'bc6_4_09', 'caller': 'guppy'},
    {'dataset': 'bc6_4_10', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_18', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_19', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_20', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_21', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_22', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_23', 'caller': 'guppy'},
    # {'dataset': 'bc7_1_24', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_18', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_19', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_20', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_21', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_22', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_23', 'caller': 'guppy'},
    # {'dataset': 'bc7_2_24', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_11', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_12', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_15', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_16', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_19', 'caller': 'guppy'},
    # {'dataset': 'sca8_1_20', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_11', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_12', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_15', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_16', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_19', 'caller': 'guppy'},
    # {'dataset': 'sca8_2_20', 'caller': 'guppy'},

    # Dorado
    # {'dataset': 'bc3_01', 'caller': 'dorado'},
    # {'dataset': 'bc3_02', 'caller': 'dorado'},
    # {'dataset': 'bc3_03', 'caller': 'dorado'},
    # {'dataset': 'bc6_05', 'caller': 'dorado'},
    # {'dataset': 'bc6_06', 'caller': 'dorado'},
    # {'dataset': 'bc6_07', 'caller': 'dorado'},
    # {'dataset': 'bc6_08', 'caller': 'dorado'},
    # {'dataset': 'bc6_09', 'caller': 'dorado'},
    # {'dataset': 'bc6_10', 'caller': 'dorado'},

    # Dorado HAC
    # {'dataset': 'bc7_1_18', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_19', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_20', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_21', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_22', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_23', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_1_24', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_18', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_19', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_20', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_21', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_22', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_23', 'caller': 'dorado_hac'},
    # {'dataset': 'bc7_2_24', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_11', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_12', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_15', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_16', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_19', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_1_20', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_11', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_12', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_15', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_16', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_19', 'caller': 'dorado_hac'},
    # {'dataset': 'sca8_2_20', 'caller': 'dorado_hac'},

    # Dorado SUP
    # {'dataset': 'bc7_1_18', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_19', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_20', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_21', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_22', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_23', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_1_24', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_18', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_19', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_20', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_21', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_22', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_23', 'caller': 'dorado_sup'},
    # {'dataset': 'bc7_2_24', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_11', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_12', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_15', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_16', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_19', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_1_20', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_11', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_12', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_15', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_16', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_19', 'caller': 'dorado_sup'},
    # {'dataset': 'sca8_2_20', 'caller': 'dorado_sup'},
]

### DMPK

In [2]:
fwd_start = 'CGGAGGACGAGGTCAATAAA'
fwd_end = 'GAGACAGAACAACGGCGAAC'
fwd_flank_pre = 'CGGAGGACGAGGTCAATAAATATCCAAACCGCCGAAGCGGGCGGAGCCGGCTGGGGCTCCGAGAGCAGCGCAAGTGAGGAGGGGGGCGCGGGATCCCCGAAAAAGCGGGTTTGGCAAAAGCAAATTTCCCGAGTAAGCAGGCAGAGATCGCGCCAGACGCTCCCCAGAGCAGGGCGTCATGCACAAGAAAGCTTTGCACTTTGCGAACCAACGATAGGTGGGGGTGCGTGGAGGATGGAACACGGACGGCCCGGCTTGCTGCCTTCCCAGGCCTGCAGTTTGCCCATCCACGTCAGGGCCTCAGCCTGGCCGAAAGAAAGAAATGGTCTGTGATCCCCC'
fwd_insert_20 = 'CAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG'
fwd_flank_suf = 'CATTCCCGGCTACAAGGACCCTTCGAGCCCCGTTCGCCGGCCGCGGACCCGGCCCCTCCCTCCCCGGCCGCTAGGGGGCGGGCCCGGATCACAGGACTGGAGCTGGGCGGAGACCCACGCTCGGAGCGGTTGTGAACTGGCAGGCGGTGGGCGCGGCTTCTGTGCCGTGCCCCGGGCACTCAGTCTTCCAACGGGGCCCCGGAGTCGAAGACAGTTCTAGGGTTCAGGGAGCGCGGGCGGCTCCTGGGCGGCGCCAGACTGCGGTGAGTTGGCCGGCGTGGGCCACCAACCCAATGCAGCCCAGGGCGGCGGCACGAGACAGAACAACGGCGAAC'
fwd_PCR = fwd_flank_pre + fwd_insert_20 + fwd_flank_suf

rev_start = 'GTTCGCCGTTGTTCTGTCTC'
rev_end = 'TTTATTGACCTCGTCCTCCG'
rev_flank_pre = 'GTTCGCCGTTGTTCTGTCTCGTGCCGCCGCCCTGGGCTGCATTGGGTTGGTGGCCCACGCCGGCCAACTCACCGCAGTCTGGCGCCGCCCAGGAGCCGCCCGCGCTCCCTGAACCCTAGAACTGTCTTCGACTCCGGGGCCCCGTTGGAAGACTGAGTGCCCGGGGCACGGCACAGAAGCCGCGCCCACCGCCTGCCAGTTCACAACCGCTCCGAGCGTGGGTCTCCGCCCAGCTCCAGTCCTGTGATCCGGGCCCGCCCCCTAGCGGCCGGGGAGGGAGGGGCCGGGTCCGCGGCCGGCGAACGGGGCTCGAAGGGTCCTTGTAGCCGGGAATG'
rev_insert_20 = 'CTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTG'
rev_flank_suf = 'GGGGGATCACAGACCATTTCTTTCTTTCGGCCAGGCTGAGGCCCTGACGTGGATGGGCAAACTGCAGGCCTGGGAAGGCAGCAAGCCGGGCCGTCCGTGTTCCATCCTCCACGCACCCCCACCTATCGTTGGTTCGCAAAGTGCAAAGCTTTCTTGTGCATGACGCCCTGCTCTGGGGAGCGTCTGGCGCGATCTCTGCCTGCTTACTCGGGAAATTTGCTTTTGCCAAACCCGCTTTTTCGGGGATCCCGCGCCCCCCTCCTCACTTGCGCTGCTCTCGGAGCCCCAGCCGGCTCCGCCCGCTTCGGCGGTTTGGATATTTATTGACCTCGTCCTCCG'
rev_PCR = rev_flank_pre + rev_insert_20 + rev_flank_suf

In [3]:
rev_PCR

'GTTCGCCGTTGTTCTGTCTCGTGCCGCCGCCCTGGGCTGCATTGGGTTGGTGGCCCACGCCGGCCAACTCACCGCAGTCTGGCGCCGCCCAGGAGCCGCCCGCGCTCCCTGAACCCTAGAACTGTCTTCGACTCCGGGGCCCCGTTGGAAGACTGAGTGCCCGGGGCACGGCACAGAAGCCGCGCCCACCGCCTGCCAGTTCACAACCGCTCCGAGCGTGGGTCTCCGCCCAGCTCCAGTCCTGTGATCCGGGCCCGCCCCCTAGCGGCCGGGGAGGGAGGGGCCGGGTCCGCGGCCGGCGAACGGGGCTCGAAGGGTCCTTGTAGCCGGGAATGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGGGGGGATCACAGACCATTTCTTTCTTTCGGCCAGGCTGAGGCCCTGACGTGGATGGGCAAACTGCAGGCCTGGGAAGGCAGCAAGCCGGGCCGTCCGTGTTCCATCCTCCACGCACCCCCACCTATCGTTGGTTCGCAAAGTGCAAAGCTTTCTTGTGCATGACGCCCTGCTCTGGGGAGCGTCTGGCGCGATCTCTGCCTGCTTACTCGGGAAATTTGCTTTTGCCAAACCCGCTTTTTCGGGGATCCCGCGCCCCCCTCCTCACTTGCGCTGCTCTCGGAGCCCCAGCCGGCTCCGCCCGCTTCGGCGGTTTGGATATTTATTGACCTCGTCCTCCG'

### SCA8

## Imports

In [4]:
from os.path import isfile, join
import statistics as stats

import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
import numpy as np
import pandas as pd
import seaborn as sns

import common

## Settings

In [5]:
pd.set_option('display.max_columns', 14)
pd.set_option('display.max_rows', 10)

## Functions

In [6]:
def count_kmers(seq):
    len_kmer = 11
    kmers = {}
    
    for i in range(len(seq) - len_kmer + 1):
        kmer = seq[i:i+len_kmer]
        if kmer in kmers:
            kmers[kmer].append(i)
        else:
            kmers[kmer] = [i]

    return {k: kmers[k][0] for k in kmers if len(kmers[k]) == 1}


def load_fastq_tsv(path):
    df = pd.read_csv(path, sep='\t', header=None)
    df.columns = ['seq', 'id']
    return df


def process_points(points, round):
    if not points:
        return [None, None, None]

    try:
        point = int(round(stats.median(points)))
        point_cnt = len(points)
        point_stdev = stats.stdev(points)
    except Exception as e:
        # raise e
        return [None, None, None]

    return [point, point_cnt, point_stdev]


def count_kmers_fastq(seq):
    len_kmer = 11
    kmers = {}
    
    for i in range(len(seq) - len_kmer + 1):
        kmer = seq[i:i+len_kmer]
        if kmer in kmers:
            kmers[kmer].append(i)
        else:
            kmers[kmer] = [i]

    fwd_starts = []
    fwd_ends = []
    rev_starts = []
    rev_ends = []
    
    for k in kmers:
        if len(kmers[k]) == 1:
            if k in FWD_PRE_KMERS:
                fwd_starts.append(339 + kmers[k][0] - FWD_PRE_KMERS[k])
            elif k in FWD_SUF_KMERS:
                fwd_ends.append(339 + kmers[k][0] - FWD_SUF_KMERS[k])
            elif k in REV_PRE_KMERS:
                rev_starts.append(335 + kmers[k][0] - REV_PRE_KMERS[k])
            elif k in REV_SUF_KMERS:
                rev_ends.append(335 + kmers[k][0] - REV_SUF_KMERS[k])
    
    fwd_start, fwd_start_cnt, fwd_start_stdev = process_points(fwd_starts, np.floor)
    fwd_end, fwd_end_cnt, fwd_end_stdev = process_points(fwd_ends, np.ceil)
    rev_start, rev_start_cnt, rev_start_stdev = process_points(rev_starts, np.floor)
    rev_end, rev_end_cnt, rev_end_stdev = process_points(rev_ends, np.ceil)

    return pd.Series({
        'fwd_start': fwd_start,
        'fwd_start_cnt': fwd_start_cnt,
        'fwd_start_stdev': fwd_start_stdev,
        'fwd_end': fwd_end,
        'fwd_end_cnt': fwd_end_cnt,
        'fwd_end_stdev': fwd_end_stdev,
        'rev_start': rev_start,
        'rev_start_cnt': rev_start_cnt,
        'rev_start_stdev': rev_start_stdev,
        'rev_end': rev_end,
        'rev_end_cnt': rev_end_cnt,
        'rev_end_stdev': rev_end_stdev,
    })


def snap_insert_fwd(row):
    if row['fwd'] == 1:
        return pd.Series({
            'prefix_flank': row['seq'][int(row['fwd_start'])-10:int(row['fwd_start'])],
            'ins': row['seq'][int(row['fwd_start']):int(row['fwd_end'])],
            'suffix_flank': row['seq'][int(row['fwd_end']):int(row['fwd_end'])+10],
        })

    return None, None, None


def snap_insert_rev(row):
    if row['rev'] == 1:
        return pd.Series({
            'prefix_flank': row['seq'][int(row['rev_start'])-10:int(row['rev_start'])],
            'ins': row['seq'][int(row['rev_start']):int(row['rev_end'])],
            'suffix_flank': row['seq'][int(row['rev_end']):int(row['rev_end'])+10],
        })

    return None, None, None

## Main

In [7]:
FWD_PRE_KMERS = count_kmers(fwd_flank_pre)
FWD_SUF_KMERS = count_kmers(fwd_flank_suf)
REV_PRE_KMERS = count_kmers(rev_flank_pre)
REV_SUF_KMERS = count_kmers(rev_flank_suf)

fwd_pre_kmers_set = set(count_kmers(fwd_flank_pre).keys())
fwd_suf_kmers_set = set(count_kmers(fwd_flank_suf).keys())
rev_pre_kmers_set = set(count_kmers(rev_flank_pre).keys())
rev_suf_kmers_set = set(count_kmers(rev_flank_suf).keys())

In [8]:
len(fwd_pre_kmers_set | fwd_suf_kmers_set | rev_pre_kmers_set | rev_suf_kmers_set)

1308

In [9]:
for k in FWD_SUF_KMERS:
    FWD_SUF_KMERS[k] += 339
for k in REV_SUF_KMERS:
    REV_SUF_KMERS[k] += 335

In [10]:
len(datasets)

6

In [11]:
res = []

for d in datasets:
    dataset = d['dataset']
    caller = d['caller']
    path = f'{fastq_tsv_path}{dataset}_{caller}.fastq.tsv'
    df_fastq = load_fastq_tsv(path)
    df_fastq['dataset'] = dataset
    df_fastq['caller'] = caller
    # reads = len(df_fastq)
    df_fastq = pd.concat([df_fastq, df_fastq.apply(lambda x: count_kmers_fastq(x['seq']), axis=1)], axis=1)
    
    df_fastq['fwd'] = ((df_fastq['fwd_start'] > 0) & (df_fastq['fwd_end'] > df_fastq['fwd_start'])).astype(int)
    df_fastq['rev'] = ((df_fastq['rev_start'] > 0) & (df_fastq['rev_end'] > df_fastq['rev_start'])).astype(int)

    cond = df_fastq['fwd'] == 1
    dff = df_fastq[cond].copy()
    dff['direction'] = 'fwd'
    dff = pd.concat([dff, dff.apply(snap_insert_fwd, axis=1)], axis=1)
    dff = dff[['direction', 'id', 'prefix_flank', 'ins', 'suffix_flank', 'fwd_start_cnt', 'fwd_start_stdev', 'fwd_end_cnt', 'fwd_end_stdev']]
    dff.columns = ['direction', 'id', 'prefix_flank', 'ins', 'suffix_flank', 'start_cnt', 'start_stdev', 'end_cnt', 'end_stdev']
    
    cond = df_fastq['rev'] == 1
    dfr = df_fastq[cond].copy()
    dfr['direction'] = 'rev'
    dfr = pd.concat([dfr, dfr.apply(snap_insert_rev, axis=1)], axis=1)
    dfr = dfr[['direction', 'id', 'prefix_flank', 'ins', 'suffix_flank', 'rev_start_cnt', 'rev_start_stdev', 'rev_end_cnt', 'rev_end_stdev']]
    dfr.columns = ['direction', 'id', 'prefix_flank', 'ins', 'suffix_flank', 'start_cnt', 'start_stdev', 'end_cnt', 'end_stdev']

    df = pd.concat([dff, dfr])
    output_path = f'{kmers_tsv_path}{dataset}.{caller}.kmers.tsv'
    df.sort_values(['id', 'direction']).to_csv(output_path, sep='\t', index=False, header=False)
    
    res.append(df_fastq)

In [12]:
df = res[0]

In [13]:
df['fwd'] = ((df['fwd_start'] > 0) & (df['fwd_end'] > df['fwd_start'])).astype(int)
df['rev'] = ((df['rev_start'] > 0) & (df['rev_end'] > df['rev_start'])).astype(int)
df.groupby(['fwd', 'rev']).count()

          seq    id  dataset  caller  fwd_start  fwd_start_cnt  \
fwd rev
0   0    6482  6482     6482    6482       1913           1913
    1    1223  1223     1223    1223         19             19
1   0    1239  1239     1239    1239       1239           1239
    1       8     8        8       8          8              8

         fwd_start_stdev  ...  fwd_end_stdev  rev_start  rev_start_cnt  \
fwd rev                   ...
0   0               1913  ...            145         62             62
    1                 19  ...             23       1223           1223
1   0               1239  ...           1239         19             19
    1                  8  ...              8          8              8

         rev_start_stdev  rev_end  rev_end_cnt  rev_end_stdev
fwd rev
0   0                 62     2141         2141           2141
    1               1223     1223         1223           1223
1   0                 19        3            3              3
    1                  8        8            8              8

[4 rows x 16 columns]

In [14]:
cond = df['fwd'] == 1
df[cond].apply(snap_insert_fwd, axis=1)

,prefix_flank,ins,suffix_flank
1,ATCCCCCAGC,AGCAGCAGCAG,CGTTCCCGGC
10,GTGATACCCC,CGGCGG,CAGCAGCATT
13,TGTGATCCCC,CCAGCAGCAGCAGCAGC,ATTCCCGGCT
20,GATCCCCCCA,GCAGCAGCAGCAGC,ATTCCCGGCT
35,GATTCCCAGC,AG,CAGCAGCAGC
...,...,...,...
8915,GATCCCCCCA,GCAGCAG,CAGCAGCATT
8931,TCCCCCCAGC,AGCAGCA,GCAGCATTCC
8932,GTGATCCCCC,CCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAGCAG...,GCATTCCCGG
8944,TCCCCAGCAG,CAGCAGCAG,CATTCCCGGC
8945,TAGCAGTACC,CAGCAGCGGCGC,CGCAGCAGCA

In [15]:
cond = df['rev'] == 1
df[cond].apply(snap_insert_rev, axis=1)

,prefix_flank,ins,suffix_flank
0,TCCTTGTAGC,CGGGAATGCTGCTGCTGCTGCTG,GGGGGATCAC
12,CGGGAATGCT,GCTGCTGCTGC,TGGGGGGACA
15,GTAGCCGGGA,ATGCTGCTGCTGCTGCTG,GGGGGATCAC
21,CCGGGAATGC,TGCTGCTGCTACTA,GGGGGGATCA
22,GTAGCCGGGA,ATGCTGCTGCTGCTGCT,GGGGGGATCA
...,...,...,...
8904,GTAGCCGGGA,ATGCTGCTGCTGCTGCTGG,GGGGAATAAC
8913,GCCGGGAATG,CTGCTGCTGCTGCTGGGG,GGATCACAGA
8936,GCCGGGAATG,CTGCTGCTGCTGCTG,GGGGGATCAC
8943,GCCGGGAATG,CTGCTGCTGCTGCTGGGG,GGATCACAGA
8951,GCCGGGAATG,CTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGCTGC...,TGGGGGGATC